#!/bin/bash
sudo env PATH="$PATH" sh -c '
    # This runs as root, but MIAB_USER_DIR is available
    # if [ ! -d "$MIAB_USER_DIR/dependencies" ]; then
    #    mkdir -p "$MIAB_USER_DIR/dependencies"
    # fi
    miab "setup/start.sh"
'
